version: '2'

services:
  tsdbrelay:
    #image: leapar/librenms:1.27
    build: ./tsdbrelay
    ports:
      - "4242:4242"
    #volumes:
    #  - ./directory/logs:/opt/librenms/logs \
    #  - ./directory/rrd:/opt/librenms/rrd \
    #environment:
    #  - DB_HOST=db
    #  - DB_NAME=librenms
    #  - DB_USER=librenms
    #  - DB_PASS=wangwang
    #  - POLLERS=16
    #  - BASE_URL=http://localhost:9080
    links:
      - bosun:bosun
    depends_on:
      - bosun
    command: tsdbrelay -b bosun:8101 -t 172.29.231.177:4243 
    restart: always
  bosun:
    build: ./bosun
    command: bosun -c /etc/bosun/bosun.toml -r true
    ports:
      - "8101:8101"
    restart: always  
    #volumes:
    #  - /directory/mysql:/var/lib/mysql
    #environment:
    #  - MYSQL_ROOT_PASSWORD=wangwang